### ISSUE TITLE
Minikube config won't be correct for all users

### ISSUE THREAD

**Issue by david-smith-ft** [Financial-Times/content-k8s-auth-setup#35]
The IP address of the server will differ between installations
Example from my config:
```
- cluster:
    certificate-authority: /Users/david.smith/.minikube/ca.crt
    server: https://192.168.64.2:8443
  name: minikube
```
